apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-id
resources:
  - ../../base
  - resources.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: pocket-id
      spec:
        template:
          spec:
            containers:
              - name: pocket-id
                env:
                  - name: APP_URL
                    value: https://pocket-id.o.cavnet.cloud
  - patch: |-
      - op: replace
        path: /spec/data/0/remoteRef/key
        value: /talos-prod/pocket-id-encryption-key
    target:
      kind: ExternalSecret
  - patch: |-
      - op: replace
        path: /spec/parentRefs/0
        value:
          namespace: default
          name: private-gateway
          sectionName: websecure
      - op: replace
        path: /spec/hostnames/0
        value: pocket-id.o.cavnet.cloud
    target:
      kind: HTTPRoute
