section: TrustDomainServerAttestation
schema: v1
spec:
  requiredAttestors:
    - type: k8s_token
      config:
        issuerURL: https://oidc.cavnet.io
        serviceAccountNamespace: tdd-kwtfbnrvlf
        serviceAccountName: tdd-kwtfbnrvlf-spirl-server
