apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: keycloak
    version: 24.4.13
    namespace: keycloak
    valuesFile: values.yaml
resources:
  - rolebinding.yaml
