apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dan.t.cavallaro@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-key
    solvers:
      - dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z05015042OJX42009787V
