apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: default
  name: any.o.cavnet.cloud-cert
spec:
  secretName: any.o.cavnet.cloud-cert
  dnsNames:
    - "*.o.cavnet.cloud"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
