apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: internet
  name: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: internet
  name: nginx-demo
#  annotations:
#    "coredns.io/hostname": lb.o.cavnet.cloud
spec:
  type: ClusterIP
  #type: LoadBalancer
  selector:
    app: nginx-demo
  ports:
    - port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  namespace: internet
  name: nginx-demo
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external-gateway
  hostnames:
    - nginx.cavnet.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-demo
          port: 80
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: nginx-demo
#spec:
#  rules:
#    - host: nginx.o.cavnet.cloud
#      http:
#        paths:
#          - pathType: Prefix
#            path: "/"
#            backend:
#              service:
#                name: nginx-demo
#                port:
#                  number: 80
