- name: Start UPS driver
  become: true
  ansible.builtin.command: upsdrvctl start

- name: Start nut-server
  become: true
  ansible.builtin.systemd_service:
    name: nut-server
    state: restarted
