apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync
helmCharts:
  - name: volsync
    repo: https://backube.github.io/helm-charts
    releaseName: volsync
    version: 0.12.1
    namespace: volsync
    includeCRDs: true
    valuesInline:
      metrics:
        disableAuth: true
resources:
  - resources.yaml
