apiVersion: v1
kind: ServiceAccount
metadata:
  name: volsync-metrics-exporter
  namespace: volsync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volsync-metrics-reader
rules:
  - apiGroups: ["volsync.backube"]
    resources: ["replicationsources"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volsync-metrics-reader
subjects:
  - kind: ServiceAccount
    name: volsync-metrics-exporter
    namespace: volsync
roleRef:
  kind: ClusterRole
  name: volsync-metrics-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volsync-metrics-exporter
  namespace: volsync
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: volsync-metrics-exporter
  template:
    metadata:
      labels:
        app: volsync-metrics-exporter
    spec:
      serviceAccountName: volsync-metrics-exporter
      containers:
        - name: exporter
          image: ghcr.io/dancavallaro/telemetry/volsync-metrics:0.2.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: volsync-metrics-exporter
  namespace: volsync
spec:
  ports:
    - port: 8080
  selector:
    app: volsync-metrics-exporter
