apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: authentik
spec:
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2025.2.0
      helm:
        valueFiles:
          - $values/k8s/manifests/authentik/values.yaml
    - repoURL: https://github.com/dancavallaro/rpi-config
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
