apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: aws-iamra-manager
spec:
  project: default
  sources:
    - repoURL: https://dancavio.github.io/aws-iamra-manager/
      chart: aws-iamra-manager
      targetRevision: 1.1.0
      helm:
        valueFiles:
          - $values/k8s/manifests/aws-iamra-manager/values.yaml
    - repoURL: https://github.com/dancavallaro/rpi-config
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: aws-iamram-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
