apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: volsync
spec:
  project: default
  source:
    repoURL: https://github.com/dancavallaro/rpi-config
    targetRevision: HEAD
    path: k8s/manifests/volsync
  destination:
    server: https://kubernetes.default.svc
    namespace: volsync
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
