apiVersion: v1
kind: Service
metadata:
  name: hass-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8123
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: hass-proxy
  labels:
    kubernetes.io/service-name: hass-proxy
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8123
endpoints:
  - addresses:
      - "192.168.5.100"
    conditions: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hass-proxy
spec:
  parentRefs:
    - namespace: default
      name: private-gateway
      sectionName: websecure
  hostnames:
    - ha.o.cavnet.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hass-proxy
          port: 80
