apiVersion: v1
kind: Service
metadata:
  name: mqtt-proxy
  annotations:
    "coredns.io/hostname": mqtt.o.cavnet.cloud
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mqtt-proxy
  labels:
    kubernetes.io/service-name: mqtt-proxy
addressType: IPv4
ports:
  - protocol: TCP
    port: 1883
endpoints:
  - addresses:
      - "192.168.5.100"
    conditions: {}
