apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: "https://argocd.o.cavnet.cloud"
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
  kustomize.buildOptions: "--enable-helm"
  oidc.config: |
    name: Authentik
    issuer: https://authentik.o.cavnet.cloud/application/o/argocd/
    clientID: i6E4gO2hYq9uhrLuuT0u2HMwDUZjzGTbgHQ85eHL
    # TODO: this shouldn't be in source control lol
    clientSecret: IBITpp6tjwzcw2JIXB30Ru71osVl23CABJ45Uz94tubUHQhW8nqn7QY84k29864U8I8HG4CKhtgbysmYU872nUVq0lzOSkqVWhXkkGNxQx2hR1sY2KMAiurI4aoj5AcS
