apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # ArgoCD logs are really chatty so turn them all down
  controller.log.level: "warn"
  server.log.level: "warn"
  reposerver.log.level: "warn"
  commitserver.log.level: "warn"
  dexserver.log.level: "warn"
  applicationsetcontroller.log.level: "warn"
  notificationscontroller.log.level: "warn"
