machine:
  install:
    disk: /dev/vda
    image: ghcr.io/dancavallaro/talos/installer:v1.9.5
  network:
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
  kubelet:
    nodeIP:
      validSubnets:
        # Make sure the kubelet gets assigned an IP from the VM subnet
        - 192.168.42.0/24
  features:
    nodeAddressSortAlgorithm: v2
# Use Cilium as CNI and kube-proxy replacement
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
