machine:
  install:
    disk: /dev/vda
    image: ghcr.io/dancavallaro/talos/installer:v1.9.5-bluetooth-iscsi # Custom build with BT modules/firmware and iSCSI support
    extraKernelArgs:
      - talos.logging.kernel=tcp://127.0.0.1:32412/
  network:
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
  kubelet:
    nodeIP:
      validSubnets:
        # Make sure the kubelet gets assigned an IP from the VM subnet
        - 192.168.42.0/24
  features:
    nodeAddressSortAlgorithm: v2
  logging:
    destinations:
      - endpoint: "tcp://127.0.0.1:32411/"
        format: "json_lines"
# Use Cilium as CNI and kube-proxy replacement
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
