apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-oidc
  namespace: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  dataFrom:
    - extract:
        key: /talos-prod/minio-oidc-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
  namespace: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  dataFrom:
    - extract:
        key: /talos-prod/minio-creds
