apiVersion: v1
kind: Namespace
metadata:
  name: heartbeats
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: heartbeats-mqtt-creds
  namespace: heartbeats
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  dataFrom:
    - extract:
        key: /talos-prod/heartbeats-mqtt-creds
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: heartbeats
  namespace: heartbeats
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: heartbeats
  template:
    metadata:
      labels:
        app: heartbeats
      annotations:
        cloud.dancav.io/aws-iamra-role-profile: heartbeats-role
        cloud.dancav.io/aws-iamra-cert-secret: heartbeats-cert
    spec:
      containers:
        - name: heartbeat-exporter
          image: ghcr.io/dancavallaro/telemetry/heartbeats:0.2.0
          envFrom:
            - secretRef:
                name: heartbeats-mqtt-creds
          args:
            - -mqttAddress
            - mqtt.mosquitto:1883
            - -mqttUsername
            - "$(username)"
            - -mqttPassword
            - "$(password)"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: heartbeat-exporter
  namespace: heartbeats
spec:
  ports:
    - port: 8080
  selector:
    app: heartbeats
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-heartbeat
  namespace: heartbeats
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: cluster-heartbeat
  template:
    metadata:
      labels:
        app: cluster-heartbeat
      annotations:
        cloud.dancav.io/aws-iamra-role-profile: heartbeats-role
        cloud.dancav.io/aws-iamra-cert-secret: heartbeats-cert
    spec:
      containers:
        - name: heartbeats
          image: ghcr.io/dancavallaro/telemetry/cluster-heartbeat:0.1.0
          args:
            - -region
            - us-east-1
            - -metricNamespace
            - KubernetesMonitoring