authentik:
  secret_key: "IbypwRp24EtJ4p+6Zw97ACXFne3D6JYMKqvcgqOulkqCkonNpUk4WrObTVHjlNX/ifBQQVlwaTVVK7Rm"
  postgresql:
    password: "VLFcLBZdB7GADqFPW3f8vqZvOLV6M3cyvX8U2xG01iBAizOnl4fGERo09baPjsFDYWNHOU8iUsOFTswK"
  error_reporting:
    enabled: false
server:
  ingress:
    ingressClassName: cilium
    enabled: true
    hosts:
      - authentik.o.cavnet.cloud
postgresql:
  enabled: true
  auth:
    password: "VLFcLBZdB7GADqFPW3f8vqZvOLV6M3cyvX8U2xG01iBAizOnl4fGERo09baPjsFDYWNHOU8iUsOFTswK"
redis:
  enabled: true
