apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: farm-notifier
  name: farm-notifier
spec:
  schedule: "- - - - -"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: farm-notifier
        spec:
          serviceAccountName: farm-notifier
          restartPolicy: OnFailure
          containers:
            - name: farm-notifier
              image: ghcr.io/dancavallaro/farm-notifier/farm-notifier:0.4.1
              args:
                - REPLACEME
              env:
                - name: AWS_DEFAULT_REGION
                  value: us-east-1
                - name: S3_ENDPOINT_URL
                  value: http://rustfs-svc.rustfs:9000
                - name: AWS_ENDPOINT_URL_STS
                  value: http://rustfs-svc.rustfs:9000
                - name: AWS_ROLE_ARN
                  value: arn:aws:iam::000000000000:role/rustfs
                - name: AWS_WEB_IDENTITY_TOKEN_FILE
                  value: /var/run/secrets/rustfs/token
                - name: SOURCE_BUCKET_NAME
                  value: farm-notifier-website-source
                - name: EMAILS_ENABLED
                  value: "true"
                - name: DATA_PATH_PREFIX
                  value: /farm-notifier/data
              volumeMounts:
                - mountPath: /farm-notifier/data
                  name: farm-notifier-data
                - mountPath: /var/run/secrets/rustfs
                  name: rustfs-token
          volumes:
            - name: farm-notifier-data
              persistentVolumeClaim:
                claimName: farm-notifier-data
            - name: rustfs-token
              projected:
                sources:
                  - serviceAccountToken:
                      audience: rustfs
                      expirationSeconds: 3600
                      path: token
