apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: farm-notifier
  name: farm-notifier
spec:
  schedule: "- - - - -"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: farm-notifier
          annotations:
            cloud.dancav.io/aws-iamra-role-profile: farm-notifier-role
            cloud.dancav.io/aws-iamra-cert-secret: farm-notifier-cert
        spec:
          restartPolicy: OnFailure
          containers:
            - name: farm-notifier
              image: ghcr.io/dancavallaro/farm-notifier/farm-notifier:0.3.1
              args:
                - REPLACEME
              env:
                - name: AWS_DEFAULT_REGION
                  value: us-east-1
                - name: S3_ENDPOINT_URL
                  value: http://minio.minio:9000
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: minio-creds
                      key: access-key
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-creds
                      key: secret-key
                - name: SOURCE_BUCKET_NAME
                  value: farm-notifier-website-source
                - name: EMAILS_ENABLED
                  value: "true"
                - name: DATA_PATH_PREFIX
                  value: /farm-notifier/data
              volumeMounts:
                - mountPath: /farm-notifier/data
                  name: farm-notifier-data
          volumes:
            - name: farm-notifier-data
              persistentVolumeClaim:
                claimName: farm-notifier-data
