
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  light:
    - name: "Hatch"
      command_topic: "nursery/hatch"
      state_topic: "nursery/hatch/state"
    - name: "Stars"
      command_topic: "nursery/stars"
      state_topic: "nursery/stars/state"
    - name: "Twinkling Stars"
      command_topic: "nursery/twinkling_stars"
      state_topic: "nursery/twinkling_stars/state"
    - name: "Penny's Stove"
      command_topic: "pennyskitchen/stove"
      state_topic: "pennyskitchen/stove/state"
    - name: "Penny's Kitchen Lights"
      command_topic: "pennyskitchen/lights"
      state_topic: "pennyskitchen/lights/state"
    - name: "Penny's Dance Party"
      command_topic: "pennyskitchen/dance_party"
      state_topic: "pennyskitchen/dance_party/state"
