apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  namespace: internet
  name: external-gateway
spec:
  gatewayClassName: traefik-external
  listeners:
    - name: web
      protocol: HTTP
      port: 8000
