apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - alertmanager.yaml
  - mimir.yaml
  - loki.yaml
  - alloy.yaml
  - grafana.yaml
configMapGenerator:
  - name: alloy-conf
    files:
      - conf/alloy/common.alloy
      - conf/alloy/podlogs.alloy
      - conf/alloy/clusterevents.alloy
