apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - common.yaml
  - alertmanager.yaml
  - mimir.yaml
  - loki.yaml
  - alloy.yaml
  - grafana.yaml
  - kube-state-metrics.yaml
configMapGenerator:
  - name: alloy-conf
    files:
      - conf/alloy/common.alloy
      - conf/alloy/pod-logs.alloy
      - conf/alloy/cluster-events.alloy
      - conf/alloy/cluster-metrics.alloy
  - name: alloy-talos-conf
    files:
      - conf/alloy/common.alloy
      - conf/alloy/talos-logs.alloy
      - conf/alloy/node-metrics.alloy
