- name: Restart rsyslog
  become: true
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted

- name: Restart journald
  become: true
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted