services:
  credential-refresher:
    container_name: credential-refresher
    restart: unless-stopped
    image: "ghcr.io/dancavallaro/rpi-config/credential-refresher:latest"
    command: ["-configDir", "/etc/credential-refresher"]
    volumes:
      - /etc/credential-refresher:/etc/credential-refresher:ro
      - /root/.aws/credentials:/root/.aws/credentials:ro
      - /home/pi/.aws/credentials:/home/pi/.aws/credentials
      - /home/s3backups/.aws/credentials:/home/s3backups/.aws/credentials
  telegraf:
    container_name: telegraf
    restart: unless-stopped
    image: "telegraf:1.31.2"
    networks:
      - telemetry
    # docker group gid, from: stat -c '%g' /var/run/docker.sock
    user: "telegraf:991"
    hostname: rpi
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
    command: ["telegraf", "--config", "/telegraf/config/telegraf.conf", "--config-directory", "/telegraf/config/telegraf.d"]
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/utmp:/var/run/utmp:ro
      - telegraf:/telegraf
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: "grafana/grafana-enterprise:11.0.2-ubuntu"
    networks:
      - telemetry
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_PATHS_CONFIG: "/var/lib/grafana/grafana.ini"
  influxdb:
    container_name: influxdb
    restart: unless-stopped
    image: "influxdb:2.7.9"
    networks:
      - telemetry
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "admin=="
      DOCKER_INFLUXDB_INIT_ORG: home
      DOCKER_INFLUXDB_INIT_BUCKET: home
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
  loki:
    container_name: loki
    restart: unless-stopped
    image: "grafana/loki:2.9.10"
    networks:
      - telemetry
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - loki-data:/loki
      - loki-config:/etc/loki
  promtail:
    container_name: promtail
    restart: unless-stopped
    image: "grafana/promtail:2.9.10"
    networks:
      - telemetry
    ports:
      - "1514:1514"
    volumes:
      - promtail:/etc/promtail
volumes:
  telegraf:
  grafana:
  influxdb-data:
  influxdb-config:
  loki-data:
  loki-config:
  promtail:
networks:
  telemetry:
