services:
  telegraf:
    container_name: telegraf
    restart: unless-stopped
    image: telegraf:1.34.1
    networks:
      - telemetry
    # docker group gid, from: stat -c '%g' /var/run/docker.sock
    user: telegraf:{{ docker_gid.stdout }}
    privileged: true
    hostname: {{ inventory_hostname }}
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
    command: ["telegraf", "--config", "/etc/telegraf/telegraf.toml"]
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/utmp:/var/run/utmp:ro
      - /run/udev:/run/udev:ro
      - ./telegraf:/etc/telegraf
  promtail:
    container_name: promtail
    restart: unless-stopped
    image: grafana/promtail:2.9.10
    command: ["-config.file=/etc/promtail/config.yaml"]
    networks:
      - telemetry
    ports:
      - "1514:1514"
    volumes:
      - ./promtail:/etc/promtail
networks:
  telemetry:
