services:
  alloy:
    container_name: alloy
    restart: unless-stopped
    privileged: true
    network_mode: host
    image: grafana/alloy:v1.7.5
    command:
      - run
      - --server.http.listen-addr=127.0.0.1:12345
      - /etc/alloy.d
    volumes:
      - /:/host/root:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /run/udev/data:/host/udev:ro
      - ./alloy:/etc/alloy.d
  promtail:
    container_name: promtail
    restart: unless-stopped
    image: grafana/promtail:2.9.10
    command: ["-config.file=/etc/promtail/config.yaml"]
    ports:
      - "1514:1514"
    volumes:
      - ./promtail:/etc/promtail
