services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:2024.1.6"
    volumes:
      - homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  mosquitto:
    image: "eclipse-mosquitto:2.0.18"
    container_name: mosquitto
    volumes:
      - mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  ring-mqtt:
    container_name: ring-mqtt
    restart: unless-stopped
    image: "tsightler/ring-mqtt:5.6.3"
    network_mode: host
    volumes:
      - ring-mqtt:/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
  flicd:
    container_name: flicd
    restart: unless-stopped
    image: "ghcr.io/dancavallaro/rpi-config/flicd:latest"
    command: ["-f", "/data/flic.sqlite3", "-s", "0.0.0.0", "-p", "5551"]
    privileged: true
    network_mode: host
    volumes:
      - flicd:/data
  serial_logger:
    container_name: serial_logger
    restart: unless-stopped
    image: "ghcr.io/dancavallaro/telemetry/serial_logger:latest"
    command: ["-device", "/dev/ttyUSB0"]
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
  heartbeats:
    container_name: heartbeats
    restart: unless-stopped
    image: "ghcr.io/dancavallaro/telemetry/heartbeats:latest"
    command:
      - "-region"
      - "us-east-1"
      - "-mqttAddress"
      - "mosquitto:1883"
      - "-mqttUsername"
      - "rpi"
      - "-mqttPassword"
      - "DHV6x48uBtYI83Ppu0tEWBmH"
      - "-metricNamespace"
      - "RPiMonitoring"
    volumes:
      - /home/pi/.aws/credentials:/root/.aws/credentials:ro
  credential-refresher:
    container_name: credential-refresher
    restart: unless-stopped
    image: "ghcr.io/dancavallaro/rpi-config/credential-refresher:latest"
    command: ["-configDir", "/etc/credential-refresher"]
    volumes:
      - /etc/credential-refresher:/etc/credential-refresher:ro
      - /root/.aws/credentials:/root/.aws/credentials:ro
      - /home/pi/.aws/credentials:/home/pi/.aws/credentials
      - /home/s3backups/.aws/credentials:/home/s3backups/.aws/credentials
volumes:
  homeassistant:
  mosquitto:
  ring-mqtt:
  flicd:
