apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
  - storageclass.yaml
patches:
  - path: namespace.patch.yaml
  - path: local-path-config.patch.yaml
  - patch: |
      # Delete the default StorageClass and we'll create our own
      $patch: delete
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-path