apiVersion: v1
kind: ConfigMap
metadata:
  namespace: local-path-storage
  name: local-path-config
data:
  config.json: |-
    {
      "nodePathMap": [
        {
          "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths": ["/var/mnt/data/local-path-provisioner"]
        }
      ]
    }
