apiVersion: v1
kind: Namespace
metadata:
  name: aws-cli
---
 apiVersion: v1
 kind: ServiceAccount
 metadata:
   namespace: aws-cli
   name: aws-cli
   annotations:
     eks.amazonaws.com/role-arn: arn:aws:iam::484396241422:role/S3BackupsRole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aws-cli
  name: aws-cli
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      name: aws-cli
      labels:
        app: aws-cli
    spec:
      serviceAccountName: aws-cli
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: [ "sleep", "infinity" ]
