apiVersion: v1
kind: Namespace
metadata:
  name: hass
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hass
  name: hass-data
spec:
  storageClassName: local-path-v2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: hass
  name: hass
spec:
  type: NodePort
  selector:
    app: hass
  ports:
    - port: 80
      targetPort: 8123
      nodePort: 30609
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: hass
  name: hass
spec:
  serviceName: hass
  selector:
    matchLabels:
      app: hass
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: hass
    spec:
      nodeSelector:
        network: dtcnet
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: init-config
          image: alpine:3
          command:
            - sh
            - -c
          args:
            - cp /config-tmp/* /config/
          volumeMounts:
            - mountPath: /config
              name: hass-data
            - mountPath: /config-tmp
              name: hass-config
      containers:
        - name: hass
          image: homeassistant/home-assistant:2025.4.4
          volumeMounts:
            - mountPath: /config
              name: hass-data
          ports:
            - containerPort: 8123
      volumes:
        - name: hass-data
          persistentVolumeClaim:
            claimName: hass-data
        - name: hass-config
          configMap:
            name: hass-config
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: hass
  name: hass
spec:
  parentRefs:
    - namespace: default
      name: private-gateway
      sectionName: websecure
  hostnames:
    - ha.o.cavnet.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hass
          port: 80
