apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hass
resources:
  - ha.yaml
configMapGenerator:
  - name: hass-config
    files:
      - conf/configuration.yaml
    options:
      disableNameSuffixHash: true