apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: wordpress
  name: mariadb-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  dataFrom:
    - extract:
        key: /talos-prod/wordpress-mariadb-creds
---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: www-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress
  name: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: wordpress
  name: mariadb
spec:
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb
              mountPath: /var/lib/mysql
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-creds
                  key: database
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-creds
                  key: username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-creds
                  key: password
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "true"
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb
---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress
spec:
  ports:
    - port: 9000
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: wordpress
  name: wordpress
spec:
  serviceName: wordpress
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.5-fpm
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: www-data
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-creds
                  key: username
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-creds
                  key: database
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-creds
                  key: password

      volumes:
        - name: www-data
          persistentVolumeClaim:
            claimName: www-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wordpress
  name: nginx.conf.d
data:
  wordpress.conf: |
    server {
      listen 80 default_server;
      server_name _;
      client_max_body_size 2M;
      root /var/www/html;
      index index.php index.html;

      location / {
        try_files $uri $uri/ /index.php?$args;
      }

      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass wordpress:9000;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  name: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www-data
              mountPath: /var/www/html
              readOnly: true
            - name: nginx-configs
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: www-data
          persistentVolumeClaim:
            claimName: www-data
        - name: nginx-configs
          configMap:
            name: nginx.conf.d
---
apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: wordpress
  name: wordpress
spec:
  parentRefs:
    - namespace: default
      name: private-gateway
      sectionName: websecure
    - name: public-gateway
      namespace: internet
      sectionName: webpublic
  hostnames:
    - bakingchallenge.o.cavnet.cloud
    - bakingchallenge.cavnet.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx
          port: 80
