apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: pocket-id-data-restore
  namespace: pocket-id
spec:
  trigger:
    manual: restore-once
  restic:
    repository: volsync-config--pocket-id-data
    destinationPVC: pocket-id-data
    copyMethod: Direct
    storageClassName: synology-iscsi
    moverPodLabels:
      cloud.dancav.io/privileged-volsync-mover: "true"
