apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-archiver
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cluster-archiver
          annotations:
            cloud.dancav.io/aws-iamra-role-profile: cluster-archiver-role
            cloud.dancav.io/aws-iamra-cert-secret: cluster-archiver-cert
        spec:
          restartPolicy: OnFailure
          containers:
            - env:
                - name: NODE_IP
                  valueFrom:
                    fieldRef:
                      fieldPath:
                        status.hostIP
              image: ghcr.io/dancavallaro/rpi-config/cluster-archiver:0.1.1
              name: cluster-archiver
              volumeMounts:
                - mountPath: /var/run/secrets/talos.dev
                  name: talos-secrets
          volumes:
            - name: talos-secrets
              secret:
                secretName: cluster-archiver-talos-secrets
