apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-archiver
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cluster-archiver
            cloud.dancav.io/aws-iamra-session-name: cluster-archiver-creds
            cloud.dancav.io/aws-iamra-cert-secret: cluster-archiver-cert
        spec:
          restartPolicy: OnFailure
          containers:
            - env:
                - name: NODE_IP
                  valueFrom:
                    fieldRef:
                      fieldPath:
                        status.hostIP
              command:
                - sh
                - -c
                - time /scripts/init.sh && time /scripts/backup.sh
              image: alpine:3
              name: cluster-archiver
              volumeMounts:
                - name: backup-scripts
                  mountPath: /scripts/
                - mountPath: /var/run/secrets/talos.dev
                  name: talos-secrets
          volumes:
            - name: backup-scripts
              configMap:
                name: backup-scripts
                optional: false
                defaultMode: 0744
            - name: talos-secrets
              secret:
                secretName: cluster-archiver-talos-secrets
