apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-archiver
resources:
  - resources.yaml
  - job.yaml
configMapGenerator:
  - name: backup-scripts
    files:
      - init.sh
      - backup.sh
