apiVersion: v1
kind: Namespace
metadata:
  name: cluster-archiver
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: cluster-archiver-talos-secrets
spec:
  roles:
    - os:admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-archiver
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::484396241422:role/S3BackupsRole
