apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: argocd
  name: argocd-server
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.o.cavnet.cloud`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.o.cavnet.cloud`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
---
# This is just a dummy Ingress so that dns-gateway can create a DNS record
# for this FQDN pointing to the Traefik LB IP (since dns-gateway doesn't support
# Traefik IngressRoutes).
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: argocd-server-dummy
spec:
  ingressClassName: traefik
  rules:
    - host: argocd.o.cavnet.cloud
