domain: o.cavnet.cloud
watchedResources:
  - Ingress
  - Service
  - HTTPRoute
  - TLSRoute
  - GRPCRoute
service:
  annotations:
    "lbipam.cilium.io/ips": 172.16.42.53
image:
  registry: ghcr.io
  repository: k8s-gateway/k8s_gateway
  tag: 1.3.0
