apiVersion: v1
kind: Namespace
metadata:
  name: nut-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nut-exporter
  namespace: nut-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nut-exporter
  template:
    metadata:
      labels:
        app: nut-exporter
    spec:
      containers:
        - name: exporter
          image: ghcr.io/druggeri/nut_exporter:3.2.0
          args:
            - --web.listen-address=:8080
            - --nut.server=10.42.42.5
            - --nut.vars_enable=battery.charge,battery.voltage,battery.voltage.nominal,battery.runtime,input.voltage,input.voltage.nominal,ups.load,ups.status
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nut-exporter
  namespace: nut-exporter
spec:
  ports:
    - port: 8080
  selector:
    app: nut-exporter