apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-issuer
spec:
  selfSigned: {}
---
# When this cert gets rotated, need to update the IAM RA trust anchor config.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-issuer-ca
  namespace: cert-manager
spec:
  duration: 8766h # 1 year
  renewBeforePercentage: 99
  isCA: true
  commonName: self-signed-issuer-ca
  secretName: self-signed-issuer-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# At the moment this is only used to issue certificates that I use with AWS IAM RA.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-ca-issuer
spec:
  ca:
    secretName: self-signed-issuer-ca
