apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
spec:
  renewBeforePercentage: 99
  secretName: test-cert
  dnsNames:
    - test-cert.o.cavnet.cloud
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
