crds:
  enabled: true
podAnnotations:
  # TODO: There's a chicken and egg problem when installing cert-manager for the first time:
  # letsencrypt-issuer-cert needs to be created by cert-manager, so it doesn't exist the first
  # time this is installed, so the cert-manager pod will fail to start. Either it needs to be
  # installed first with these annotations disabled and then installed again with them enabled,
  # or need to use 2 cert-manager instances.
  cloud.dancav.io/aws-iamra-session-name: letsencrypt-issuer-role
  cloud.dancav.io/aws-iamra-cert-secret: letsencrypt-issuer-cert
securityContext:
  runAsNonRoot: false
#global:
#  logLevel: 4
