apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: any.o.cavnet.cloud-cert
spec:
  renewBeforePercentage: 99
  secretName: any.o.cavnet.cloud-cert
  dnsNames:
    - "*.o.cavnet.cloud"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
