# kustomize build --enable-helm manifests/aws-iamra-manager | kubectl apply -f -
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: aws-iamra-manager
    namespace: aws-iamram-system
    releaseName: aws-iamra-manager
    repo: https://charts.o.cavnet.cloud
    version: 1.0.0
    valuesFile: values.yaml
