apiVersion: v1
kind: Service
metadata:
  name: dsm-data
  namespace: synology-csi
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: dsm-data
  namespace: synology-csi
  labels:
    kubernetes.io/service-name: dsm-data
addressType: IPv4
ports:
  - port: 5000
endpoints:
  - addresses:
      - "10.42.42.12"
---
apiVersion: v1
kind: Service
metadata:
  name: dsm-mgmt
  namespace: synology-csi
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: dsm-mgmt
  namespace: synology-csi
  labels:
    kubernetes.io/service-name: dsm-mgmt
addressType: IPv4
ports:
  - port: 5000
endpoints:
  - addresses:
      - "192.168.6.62"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dsm-mgmt
  namespace: synology-csi
spec:
  parentRefs:
    - namespace: default
      name: private-gateway
      sectionName: websecure
  hostnames:
    - nas.o.cavnet.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dsm-mgmt
          port: 80
