apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synology-csi
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/dancavallaro/synology-csi-talos/refs/heads/main/deploy/kubernetes/v1.20/csi-driver.yaml
  - https://raw.githubusercontent.com/dancavallaro/synology-csi-talos/refs/heads/main/deploy/kubernetes/v1.20/controller.yaml
  - https://raw.githubusercontent.com/dancavallaro/synology-csi-talos/refs/heads/main/deploy/kubernetes/v1.20/node.yaml
  - storageclass.yaml
  - dsm-proxy.yaml
patches:
  - target:
      kind: DaemonSet
      name: synology-csi-node
    patch: |
      - op: replace
        path: /spec/template/spec/dnsPolicy
        value: ClusterFirstWithHostNet
  - target:
      kind: StatefulSet
      name: synology-csi-controller
    patch: |
      - op: replace
        path: /spec/template/spec/dnsPolicy
        value: ClusterFirstWithHostNet
        
