apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-test-jellyfin-config
  namespace: jellyfin
spec:
  volumeSnapshotClassName: synology-iscsi-snapshot
  source:
    persistentVolumeClaimName: jellyfin-config
