apiVersion: v1
kind: Namespace
metadata:
  name: farm-notifier
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: farm-notifier
  name: farm-notifier
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::484396241422:role/produce-notifier-role
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: farm-notifier
  name: farm-notifier-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi