- name: Create user
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
- name: Create user's .aws directory
  become: true
  ansible.builtin.file:
    path: "/home/{{ item }}/.aws"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
- name: Create user's AWS credentials file
  become: true
  ansible.builtin.file:
    path: "/home/{{ item }}/.aws/credentials"
    state: touch
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '600'