- name: Bootstrap RPi
  hosts: all
  tasks:
    - name: Sanity check
      ansible.builtin.ping:
    - name: Install apt packages
      become: true
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - vim
          - curl
          - ca-certificates
          - lm-sensors
          - jq
          - sqlite3
          - rsyslog
    - name: Clone rpi-config repo
      ansible.builtin.git:
        repo: git@github.com:dancavallaro/rpi-config.git
        dest: ~/rpi-config
        accept_newhostkey: true
        version: main
    - name: Install .vimrc
      ansible.builtin.file:
        src: ~/rpi-config/dotfiles/vimrc
        dest: ~/.vimrc
        state: link
        force: true
    - name: Install .gitconfig
      ansible.builtin.file:
        src: ~/rpi-config/dotfiles/gitconfig
        dest: ~/.gitconfig
        state: link
        force: true
    - name: Create virtual env
      become: true
      ansible.builtin.command: python3 -m venv /usr/local/rpi-config/.venv
    - name: Install dependencies for Python scripts
      become: true
      ansible.builtin.pip:
        requirements: "{{ ansible_user_dir }}/rpi-config/requirements.txt"
        executable: /usr/local/rpi-config/.venv/bin/pip
    - name: Copy scripts
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: "{{ ansible_user_dir }}/rpi-config/bin"
        dest: /usr/local/rpi-config
        mode: '755'
    - name: Install AWS CLI
      become: true
      ansible.builtin.command: "{{ ansible_user_dir }}/rpi-config/ansible/install-aws-cli"
    - name: Install Docker
      become: true
      ansible.builtin.command: "{{ ansible_user_dir }}/rpi-config/ansible/install-docker"
    - name: Add my user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true
    # This didn't actually work until I compiled the Loki driver myself:
    # https://github.com/grafana/loki/issues/974#issuecomment-1684801986
    - name: Install Loki Docker driver
      ansible.builtin.command: "docker plugin install grafana/loki-docker-driver:2.9.10 --alias loki --grant-all-permissions"
    - name: Install Docker daemon config with Loki logging
      become: true
      ansible.builtin.copy:
        src: files/etc/docker/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
    - name: Create users
      ansible.builtin.include_tasks:
        file: create-user.yaml
      loop:
        - pi
        - s3backups
    - name: Add pi user to additional groups
      become: true
      ansible.builtin.user:
        name: pi
        groups: gpio,docker,dialout
        append: true
    - name: Copy credential-refresher configs
      become: true
      ansible.builtin.copy:
        src: ../etc/credential-refresher
        dest: /etc/
        owner: root
        group: root
    - name: Install crontab
      become: true
      ansible.builtin.copy:
        src: ../etc/crontab
        dest: /etc/cron.d/rpi
        owner: root
        group: root
    - name: Install rsyslog config
      become: true
      ansible.builtin.copy:
        src: files/etc/rsyslog.conf
        dest: /etc/rsyslog.conf
        owner: root
        group: root
      notify: Restart rsyslog
      changed_when: true
    - name: Install avahi config
      become: true
      ansible.builtin.copy:
        src: files/etc/avahi/avahi-daemon.conf
        dest: /etc/avahi/avahi-daemon.conf
        owner: root
        group: root
      notify: Restart avahi
    - name: Print completion message
      ansible.builtin.debug:
        msg: Done with initial provisioning! Run SSM activation next.

  handlers:
    - name: Restart rsyslog
      ansible.builtin.systemd_service:
        name: rsyslog
        state: restarted
    - name: Restart avahi
      ansible.builtin.systemd_service:
        name: avahi-daemon
        state: restarted
