#!/usr/bin/env bash
set -euo pipefail

if command -v aws ; then
  echo "aws CLI is already installed, nothing to do"
  exit 0
fi

DIR=$(mktemp -d)

cd "$DIR"
curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
