- name: Finish provisioning after SSM activation
  hosts: all
  tasks:
    - name: Sanity check
      ansible.builtin.ping:
    - name: Install crontab
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: /home/dan/rpi-config/etc/crontab
        dest: /etc/cron.d/rpi
        owner: root
        group: root