- name: Bootstrap RPi
  hosts: all
  tasks:
    - name: Sanity check
      ansible.builtin.ping:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
    - name: Install apt packages
      become: true
      ansible.builtin.apt:
        pkg:
          - vim
    - name: Check out rpi-config repo
      ansible.builtin.git:
        repo: git@github.com:dancavallaro/rpi-config.git
        dest: ~/rpi-config
        accept_newhostkey: true
        version: main
    - name: Install .vimrc
      ansible.builtin.file:
        src: ~/rpi-config/dotfiles/vimrc
        dest: ~/.vimrc
        state: link
        force: true
    - name: Install .gitconfig
      ansible.builtin.file:
        src: ~/rpi-config/dotfiles/gitconfig
        dest: ~/.gitconfig
        state: link
        force: true
    - name: Check out telemetry repo
      ansible.builtin.git:
        repo: git@github.com:dancavallaro/telemetry.git
        dest: ~/telemetry
        accept_newhostkey: true
        version: main
    - name: Create virtual env
      ansible.builtin.command: python3 -m venv ~/rpi-config/.venv
    - name: Install dependencies for Python scripts
      ansible.builtin.pip:
        requirements: ~/rpi-config/requirements.txt
        executable: ~/rpi-config/.venv/bin/pip