#!/usr/bin/env bash

REGION=us-east-1

mkdir /tmp/ssm
curl "https://amazon-ssm-${REGION}.s3.${REGION}.amazonaws.com/latest/debian_arm/ssm-setup-cli" -o /tmp/ssm/ssm-setup-cli
sudo chmod +x /tmp/ssm/ssm-setup-cli
sudo /tmp/ssm/ssm-setup-cli -register -activation-code "activation-code" -activation-id "activation-id" -region "${REGION}"
