#!/usr/bin/env bash

REGION=us-east-1

DIR=$(mktemp -d)
curl "https://amazon-ssm-${REGION}.s3.${REGION}.amazonaws.com/latest/debian_arm64/ssm-setup-cli" -o "$DIR/ssm-setup-cli"
sudo chmod +x "$DIR/ssm-setup-cli"
sudo "$DIR/ssm-setup-cli" -register -activation-code "$1" -activation-id "$2" -region "${REGION}"
