apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      name: aws-cli
      labels:
        app: aws-cli
      annotations:
        cloud.dancav.io/aws-iamra-session-name: s3-backup-role
        cloud.dancav.io/aws-iamra-cert-secret: aws-cli-cert
    spec:
      containers:
        - name: aws-cli
          image: amazon/aws-cli
          command: [ "sleep", "infinity" ]
---
apiVersion: cloud.dancav.io/v1
kind: AwsIamRaSession
metadata:
  name: s3-backup-role
spec:
  trustAnchorArn: arn:aws:rolesanywhere:us-east-1:484396241422:trust-anchor/1acbff48-4cbe-4593-9fea-caf869c51b1a
  profileArn: arn:aws:rolesanywhere:us-east-1:484396241422:profile/cf0dca44-1d61-41d5-9963-50f3477b8b02
  roleArn: arn:aws:iam::484396241422:role/S3BackupsRole
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aws-cli
spec:
  secretName: aws-cli-cert
  duration: 24h
  renewBeforePercentage: 99
  isCA: false
  usages:
    - client auth
  dnsNames:
    - aws-cli.o.cavnet.cloud
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
