apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: dtcnet
spec:
  project: default
  source:
    repoURL: https://github.com/dancavallaro/rpi-config
    targetRevision: HEAD
    path: k8s/manifests/dtcnet
  destination:
    namespace: dtcnet
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
