apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-demo
  labels:
    app: lb-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-demo
  template:
    metadata:
      labels:
        app: lb-demo
    spec:
      containers:
        - name: lb-demo
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-demo
  annotations:
    "coredns.io/hostname": "lb-demo.o.cavnet.cloud"
spec:
  type: LoadBalancer
  selector:
    app: lb-demo
  ports:
    - port: 80
