# Set default SSL certificate (seems to only be used for Ingresses, I need to set it
# again below for the Gateway).
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  # Needs to be in default namespace, since that's where the cert secret is
  namespace: default
  name: default
spec:
  defaultCertificate:
    secretName: any.o.cavnet.cloud-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  namespace: default
  name: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 8000
    - name: websecure
      protocol: HTTPS
      port: 8443
      hostname: "*.o.cavnet.cloud"
      tls:
        certificateRefs:
          - kind: Secret
            name: any.o.cavnet.cloud-cert
