
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  light:
    - name: "Hatch"
      unique_id: "gytv2z8w"
      command_topic: "nursery/hatch"
      state_topic: "nursery/hatch/state"
    - name: "Stars"
      unique_id: "rj29d8zx"
      command_topic: "nursery/stars"
      state_topic: "nursery/stars/state"
      brightness_command_topic: "nursery/stars/brightness"
      brightness_state_topic: "nursery/stars/brightness/state"
    - name: "Twinkling Stars"
      unique_id: "hnj79a2f"
      command_topic: "nursery/twinkling_stars"
      state_topic: "nursery/twinkling_stars/state"
      brightness_command_topic: "nursery/twinkling_stars/brightness"
      brightness_state_topic: "nursery/twinkling_stars/brightness/state"
    - name: "Penny's Stove"
      unique_id: "y3k8evc5"
      command_topic: "pennyskitchen/stove"
      state_topic: "pennyskitchen/stove/state"
    - name: "Penny's Kitchen Lights"
      unique_id: "dbx2e6vc"
      command_topic: "pennyskitchen/lights"
      state_topic: "pennyskitchen/lights/state"
    - name: "Penny's Dance Party"
      unique_id: "dx8362pk"
      command_topic: "pennyskitchen/dance_party"
      state_topic: "pennyskitchen/dance_party/state"
    - name: "Classic Twinkle"
      unique_id: "f57nb26x"
      command_topic: "nursery/twinkling/mode/set"
      state_topic: "nursery/twinkling/mode/status"
      payload_on: "1"
      payload_off: "0"
    - name: "Fading Twinkle"
      unique_id: "b6na8df7"
      command_topic: "nursery/twinkling/mode/set"
      state_topic: "nursery/twinkling/mode/status"
      payload_on: "2"
      payload_off: "0"
    - name: "Fading Twinkle (w/ fade-out)"
      unique_id: "m9xtdz7c"
      command_topic: "nursery/twinkling/mode/set"
      state_topic: "nursery/twinkling/mode/status"
      payload_on: "3"
      payload_off: "0"
binary_sensor:
  - platform: flic
    host: 172.17.0.1
    discovery: false
    ignored_click_types: [double, hold]
emulated_hue:
  listen_port: 80
  expose_by_default: false
  entities:
    script.goodnight:
      hidden: false
    script.goodnight_penny:
      hidden: false
    script.goodbye:
      hidden: false
    script.good_morning:
      hidden: false
    light.stars:
      hidden: false
    light.twinkling_stars:
      hidden: false
    light.hatch:
      hidden: false
    light.pennys_dance_party:
      hidden: false

ios:
  actions:
    - name: goodnight_penny
      background_color: "#07699e"
      label:
        text: Goodnight Penny
        color: "#ffffff"
      icon:
        icon: sleep
        color: "#ffffff"
    - name: goodnight
      background_color: "#07699e"
      label:
        text: Goodnight
        color: "#ffffff"
      icon:
        icon: sleep
        color: "#ffffff"
    - name: goodbye
      background_color: "#07699e"
      label:
        text: Goodbye
        color: "#ffffff"
      icon:
        icon: hand_wave
        color: "#ffffff"
    - name: good_morning
      background_color: "#07699e"
      label:
        text: Good Morning
        color: "#ffffff"
      icon:
        icon: weather_sunny
        color: "#ffffff"
