
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  light:
    - name: "Hatch"
      command_topic: "nursery/hatch"
      state_topic: "nursery/hatch/state"
    - name: "Stars"
      command_topic: "nursery/stars"
      state_topic: "nursery/stars/state"
      brightness_command_topic: "nursery/stars/brightness"
      brightness_state_topic: "nursery/stars/brightness/state"
    - name: "Twinkling Stars"
      command_topic: "nursery/twinkling_stars"
      state_topic: "nursery/twinkling_stars/state"
      brightness_command_topic: "nursery/twinkling_stars/brightness"
      brightness_state_topic: "nursery/twinkling_stars/brightness/state"
    - name: "Penny's Stove"
      command_topic: "pennyskitchen/stove"
      state_topic: "pennyskitchen/stove/state"
    - name: "Penny's Kitchen Lights"
      command_topic: "pennyskitchen/lights"
      state_topic: "pennyskitchen/lights/state"
    - name: "Penny's Dance Party"
      command_topic: "pennyskitchen/dance_party"
      state_topic: "pennyskitchen/dance_party/state"
    - name: "Classic Twinkle"
      command_topic: "nursery/twinkling/mode/set"
      state_topic: "nursery/twinkling/mode/status"
      payload_on: "1"
      payload_off: "0"
    - name: "Fading Twinkle"
      command_topic: "nursery/twinkling/mode/set"
      state_topic: "nursery/twinkling/mode/status"
      payload_on: "2"
      payload_off: "0"
    - name: "Fading Twinkle (w/ fade-out)"
      command_topic: "nursery/twinkling/mode/set"
      state_topic: "nursery/twinkling/mode/status"
      payload_on: "3"
      payload_off: "0"
