apiVersion: v1
kind: Namespace
metadata:
  name: serial-logger
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Service
metadata:
  namespace: serial-logger
  name: serial-logger
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: serial-logger
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: serial-logger
  name: serial-logger
spec:
  serviceName: serial-logger
  selector:
    matchLabels:
      app: serial-logger
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: serial-logger
    spec:
      nodeSelector:
        hardware: esp32
      containers:
        - name: serial-logger
          image: ghcr.io/dancavallaro/telemetry/serial_logger:v0.1.3
          securityContext:
            privileged: true
          args:
            - -device
            - /dev/ttyUSB0
          volumeMounts:
            - mountPath: /dev/ttyUSB0
              name: esp32-usb
      volumes:
        - name: esp32-usb
          hostPath:
            path: /dev/ttyUSB0
