apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# TODO: figure out how to handle creation of both namespaces from ArgoCD app
namespace: minio-default
helmCharts:
  - name: tenant
    repo: https://operator.min.io
    releaseName: minio-default
    version: 7.0.1
    namespace: minio-default
    # TODO: enable ingresses for the console and API
    # TODO: configure OIDC
    # TODO: figure out how to use STS for programmatic access
    valuesInline:
      tenant:
        name: default
        configuration:
          name: minio-env-config
        configSecret:
          name: minio-env-config
        pools:
          - servers: 1
            name: default-pool
            volumesPerServer: 1
            size: 10Gi
        certificate:
          requestAutoCert: false
