apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# TODO: figure out how to handle creation of both namespaces from ArgoCD app
namespace: minio-default
helmCharts:
  - name: tenant
    repo: https://operator.min.io
    releaseName: minio-default
    version: 7.0.1
    namespace: minio-default
    # TODO: enable ingresses for the console and API
    # TODO: configure OIDC
    # TODO: figure out how to use OIDC with AWS CLI
    # TODO: figure out how to use STS for programmatic access
    valuesInline:
      tenant:
        name: default
        # TODO: can i ditch this after enabling OIDC?
        configuration:
          name: minio-temp-config
        configSecret:
          name: minio-temp-config
          accessKey: admin
          secretKey: temporary
        env:
          - name: MINIO_IDENTITY_OPENID_CONFIG_URL
            value: https://pocket-id.o.cavnet.cloud/.well-known/openid-configuration
          - name: MINIO_IDENTITY_OPENID_CLIENT_ID
            value: 875d8377-b842-4c24-9790-104bc1502135
          - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: minio-oidc-config
                key: client-secret
        pools:
          - servers: 1
            name: default-pool
            volumesPerServer: 1
            size: 10Gi
        certificate:
          # Disable TLS (fronted by ingress
          requestAutoCert: false
      extraResources: []
      ingress:
        api:
          enabled: true
          tls:
            - hosts:
              - s3.o.cavnet.cloud
          host: s3.o.cavnet.cloud
        console:
          enabled: true
          tls:
            - hosts:
              - minio.o.cavnet.cloud
          host: minio.o.cavnet.cloud
