apiVersion: v1
kind: Namespace
metadata:
  name: unifi
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unifi
  name: unifi-app-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unifi
  name: unifi-app
spec:
  selector:
    matchLabels:
      app: unifi-app
  replicas: 1
  template:
    metadata:
      labels:
        app: unifi-app
    spec:
      nodeSelector:
        network: dtcnet
      hostNetwork: true
      # Otherwise it won't be able to resolve the DB service DNS name
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: unifi-network-app
          image: lscr.io/linuxserver/unifi-network-application:9.0.108
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/New_York
            - name: MONGO_HOST
              value: unifi-db.unifi
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: unifi
            - name: MONGO_AUTHSOURCE
              value: admin
            - name: MONGO_USER
              value: unifi
            - name: MONGO_PASS
              value: unifi
          volumeMounts:
            - name: unifi-app-config
              mountPath: /config
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 8843
            - containerPort: 8880
            - containerPort: 6789
            - containerPort: 3478
              protocol: UDP
            - containerPort: 10001
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
            - containerPort: 5514
              protocol: UDP
          resources:
            requests:
              memory: "1G"
              cpu: "0.25"
            limits:
              memory: "1G"
              cpu: "0.25"
      volumes:
        - name: unifi-app-config
          persistentVolumeClaim:
            claimName: unifi-app-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: unifi
  name: unifi-app
spec:
  selector:
    app: unifi-app
  ports:
    - name: https
      targetPort: 8443
      port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: unifi
  name: unifi-app
spec:
  parentRefs:
    - namespace: default
      name: private-gateway
      sectionName: websecure
  hostnames:
    - unifi.o.cavnet.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: unifi-app
          port: 443
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-ca-cert
  namespace: unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    manifest:
      apiVersion: v1
      kind: ConfigMap
  data:
    - secretKey: ca.crt
      remoteRef:
        key: /talos-prod/unifi-ca-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: unifi-backend-tls
  namespace: unifi
spec:
  targetRefs:
    - group: ''
      kind: Service
      name: unifi-app
  validation:
    caCertificateRefs:
      - name: unifi-ca-cert
        group: ''
        kind: ConfigMap
    hostname: unifi
