apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  type: LoadBalancer
  selector:
    app: nginx-demo
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo
spec:
  rules:
    - host: nginx.o.cavnet.cloud
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx-demo
                port:
                  number: 80
  tls:
    - hosts:
        - nginx.o.cavnet.cloud
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: nginx-demo
spec:
  parentRefs:
    - name: private-gateway
      # Only attach to the HTTPS listener to enable redirect from HTTP
      sectionName: websecure
    - name: public-gateway
      namespace: internet
      sectionName: webpublic
  hostnames:
    - nginx.o.cavnet.cloud
    - nginx.cilium-poc.cavnet.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-demo
          port: 80
